<?php
/**
 * Diglin GmbH - Switzerland
 *
 * @author      Sylvain Rayé <support at diglin.com>
 * @category    Diglin
 * @package     Diglin_GoogleAnalytics
 * @copyright   Copyright (c) 2011-2016 Diglin (http://www.diglin.com)
 */

/**
 * @var $this Diglin_GoogleAnalytics_Block_Ga
 */
?>
<?php
$_helper = Mage::helper('diglin_googleanalytics');
$_accountId = $_helper->getAccountId();
?>
<?php if (!$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php if($_helper->isUseUniversalAnalytics()): ?>
        <!-- BEGIN GOOGLE UNIVERSAL ANALYTICS CODE -->
        <script type="text/javascript">
            //<![CDATA[
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            <?php echo $this->_getPageTrackingCode($_accountId) ?>
            <?php echo $this->_getOrdersTrackingCode() ?>

            //]]>
        </script>
        <!-- END GOOGLE UNIVERSAL ANALYTICS CODE -->
    <?php else: ?>
        <!-- BEGIN GOOGLE ANALYTICS CODE -->
        <script type="text/javascript">
            //<![CDATA[
            var _gaq = _gaq || [];
            <?php echo $this->_getPageTrackingCode($_accountId) ?>
            <?php echo $this->_getOrdersTrackingCode() ?>

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

            //]]>
        </script>
        <!-- END GOOGLE ANALYTICS CODE -->
    <?php endif; ?>
<?php endif; ?>
